# Category.create(code: "0", name: "総記")
# Category.create(code: "1", name: "哲学")
# Category.create(code: "2", name: "歴史")
# Category.create(code: "3", name: "社会科学")
# Category.create(code: "4", name: "自然科学")
# Category.create(code: "5", name: "技術")
# Category.create(code: "6", name: "産業")
# Category.create(code: "7", name: "芸術")
# Category.create(code: "8", name: "言語")
# Category.create(code: "9", name: "文化")

Catalog.create(category_id: 2, isbn: "4906638015", title: "7つの習慣", author: "スティーブン・R・コビー", publisher: "キングベアー出版", publish_date: "1996-12-25")
Catalog.create(category_id: 4, isbn: "4480425993", title: "よいこの君主論", author: "架神 恭介/辰巳 一世", publisher: "筑摩書房", publish_date: "2009-05-11")

Stock.create(catalog_id: 1, arrival_date: "2010-01-07", disposal_date: "", remarks: "")
Stock.create(catalog_id: 1, arrival_date: "2010-01-07", disposal_date: "", remarks: "")
Stock.create(catalog_id: 2, arrival_date: "2015-10-18", disposal_date: "", remarks: "")
Stock.create(catalog_id: 2, arrival_date: "2015-10-18", disposal_date: "", remarks: "")
Stock.create(catalog_id: 2, arrival_date: "2015-10-18", disposal_date: "", remarks: "")
